### ISSUE TITLE
FAQ all opened in Google Chroom

### ISSUE THREAD

**Issue by visenco** [mageprince/magento2-FAQ#3]
When opening the FAQ page all the FAQS are already opened, this is only in Google Chrome. I test in Mozilla and  Microsoft Edge. 

Here is an example: https://www.vizenco.nl/vnl/faq/

**Comment by mageprince** [comment]
**@visenco** , thank you for your report.
I am not able to reproduce this issue. Please try to reproduce this issue on a clean installation of Magento.

**Comment by visenco** [comment]
Is also on mobile. We are using LUMA, if you open the link in Chrome, the main questions are all closed ? So no answers showing ?

**Comment by PiroozMoridBeidokhti** [comment]
Hi Visenco, I have a similar problem like yours but in all browser and after clearing the browser cache this happens. the second time that i open my page it works fine. So the problem is just the first time i open the faq page after clearing browser cache. I think this faq module has some problems in it's js file and are not loaded sometimes. It only happens to me in the production mode not in the developer mode. put your magento2 on developer mode and see if this persists. If not, there's something with faq js file and the cache system of magento. They haven't solved my issue too and answered me the same.

**Comment by mageprince** [comment]
Hi, @visenco  And @PiroozMoridBeidokhti  Sorry for the inconvenience.
But this module does not contain any high level of js. This module only contains default accordion function of jQuery. You also can check js file here: magento2-FAQ/view/frontend/web/js/faq.js

Also, you can check these sites where this module working without any issue even with custom themes.

http://www.deshibazaar24.com/index.php/faq/
http://www.figbay.com/faq

**Comment by TeodorBogdanov** [comment]
Hi @visenco @PiroozMoridBeidokhti  did you guys find a fix for the open accordion tabs - I am having 2.2.3 magento install with a commercial Ultimo theme and after installing the FAQs, the accordion tabs work only the first time round but if you click away from the FAQ page and then go back to it - they are all as per the example https://www.vizenco.nl/vnl/faq/ (in all browsers). Any help will be appreciated!
Regards,
Teodor

**Comment by PiroozMB** [comment]
Hi Theodor do you use porto theme as well?

**Comment by TeodorBogdanov** [comment]
Not that I know off @PiroozMoridBeidokhti

**Comment by PiroozMB** [comment]
what is your email? maybe i can help but not via git this way. I could solve mine.

**Comment by TeodorBogdanov** [comment]
bogdanov.teodor@yahoo.com @PiroozMoridBeidokhti
