### ISSUE TITLE
jQueryUI Compat

### ISSUE THREAD

**Issue by Quazz** [mageprince/magento2-FAQ#36]
I believe in version 2.3.2 of Magento, they changed the jQueryUI library to modularized in order to speed up frontend page loads. 

So instead of calling the entire jQueryUI library, they call only the needed libraries.

As far as I can tell faq.js only needs `jquery-ui-modules/accordion` so calling that instead should resolve this.

**Comment by mageprince** [comment]
Hi, @Quazz Thank you for the suggestion. Your point is valid but unfortunately, we can't remove `jquery/ui` library due to backward compatible issue. `jquery-ui-modules/accordion` library is not available in Magento 2.1.x and 2.2.x and we offer this extension is supported in Magento 2.1.x, 2.2.x and 2.3.x.
